<a href="https://colab.research.google.com/github/andreyppsc/tensorflow-notebooks/blob/main/000_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover the fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using &tf.function
* Using GPUs
* Exercises

## Introduction to tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dim)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dim of the matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., .7],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  0.7],
       [ 3. ,  2. ],
       [ 8. ,  9. ]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (ex wind speed and director)
* Matrix: a 2-dim array of numbers
* Tesnor: an _**n**_-dim array of numbers (where _**n**_ can be any number)

### Creating tensors with `tf.Variable`

In [ ]:
# Create the same tensor with tf.Variable as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

In [ ]:
# How about we try .assing()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some arbitrary size which 

In [56]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproductibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [75]:
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other wasy to make tensors

In [78]:
tf.ones([10 ,7]), tf.zeros(shape=(3, 4))

(<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>)

### Turn NumPy arrays into tensors

In [81]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [87]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [88]:
A.ndim

2

### Getting information from tensors

When dealing with tensors you will have to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [100]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [110]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [114]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [123]:
# Get the first element each dimension from each index except for the final one
rank_4_tensor[1:, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [126]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[4, 5],
                             [2, 1]])

In [129]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1], dtype=int32)>

In [133]:
# Add in extra dim to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [5]],

       [[2],
        [1]]], dtype=int32)>

In [137]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [5]],

       [[2],
        [1]]], dtype=int32)>

### Manipulating tensors

**Basic operations**

`+`, `-`, `*`, `/`

In [140]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [142]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [144]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [146]:
# Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [148]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [152]:
# We can use the tensordlow builtin function too
tf.multiply(tensor, 10), tf.add(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>)

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are **two** rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimmensions

In [155]:
# Matrix multiplication in tensor flow
print(tensor)

tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [157]:
tensor * tensor # looks like it's element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [167]:
tensor_X = tf.constant([[1, 2],
                        [7, 2],
                        [3, 3]])
tensor_Y = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])

tf.matmul(tensor_X, tensor_Y)

InvalidArgumentError: ignored

In [169]:
# Let's change the shape of Y
tf.reshape(tensor_Y, (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [172]:
tensor_X @ tf.reshape(tensor_Y, (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [35, 37, 58],
       [30, 18, 42]], dtype=int32)>

In [174]:
tf.matmul(tensor_X, tf.reshape(tensor_Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [35, 37, 58],
       [30, 18, 42]], dtype=int32)>

In [176]:
tf.matmul(tf.reshape(tensor_X, (2, 3)), tensor_Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 75],
       [27, 55]], dtype=int32)>

In [178]:
# Can do the same with transpose
tf.transpose(tensor_X), tf.reshape(tensor_X, (2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 7],
        [2, 3, 3]], dtype=int32)>)

In [180]:
tf.matmul(tf.transpose(tensor_X), tensor_Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48]], dtype=int32)>

 ***The dot product***
 
Matrix multiplication is also referred as the dot product.

You can perform matrix multiplication using:
* `tf.matmul`
* `tf.tensordot`
* `@` operator - python related

In [181]:
X = tensor_X
Y = tensor_Y

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [184]:
# Using tf.tensordot
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48]], dtype=int32)>

In [186]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [31, 56, 23],
       [24, 39, 27]], dtype=int32)>

In [188]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [35, 37, 58],
       [30, 18, 42]], dtype=int32)>

In [196]:
# Check the values of Y, reshaped Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Reshaped Y:")
print(tf.reshape(Y, (2, 3)), "\n")

print("Transposed Y:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplacation on two tensors and one of the axes doesn't line up, you will transpose rather than reshape one of the tensors

### Change the datatype of a tensor

In [198]:
# Create a new tensor with a default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [200]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [204]:
# Change from float32 to float16
B = tf.cast(B, tf.float16)
B.dtype

tf.float16

In [205]:
# Change from int32 to int16
C = tf.cast(C, tf.int16)
C.dtype

tf.int16

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [209]:
# Get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggregation:
* minimum
* maximum
* mean
* sum

In [213]:
# Create a random tensor with values between 0 and 100 pf size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 5, 47, 40, 24, 62, 32, 26, 39, 98, 33,  6, 72, 96, 41, 80, 67,  9,
       18, 19, 67, 51, 32, 86, 97, 56, 42, 89, 37, 23, 22, 45, 41, 18, 40,
       58, 40, 43, 42, 93, 68,  4, 95, 63, 31, 25,  2, 68, 71, 11, 87])>

In [214]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [215]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [216]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [217]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [218]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2361>

In [220]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, tf.complex64))

<tf.Tensor: shape=(), dtype=float32, numpy=760.21155>

In [222]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, tf.complex64))

<tf.Tensor: shape=(), dtype=float32, numpy=27.571934>

In [223]:
# Find the variance using tfp
import tensorflow_probability as tfp

In [224]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=760>

In [227]:
tf.math.reduce_std(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.571934>

### Find the positional max and min of a tensor